GET https://task-manager-api-w9ye.onrender.com/api/v1/tasks

###

POST https://task-manager-api-w9ye.onrender.com/api/v1/tasks
Content-Type: application/json

{
    "name": "Kosomk"
}

###
DELETE https://task-manager-api-w9ye.onrender.com/api/v1/tasks/64d063154b28eef246378b31